### ISSUE TITLE
space

### ISSUE THREAD

**Issue by iamsuyashpatel07** [iamsuyashpatel07/suyashpatel#1]
trying to fix space between navigation bar , body & footer.

**Comment by 013himanshu** [comment]
can you describe the issue some more?

**Comment by iamsuyashpatel07** [comment]
Actually you have to add padding from top and down in clock so that it doesn't look like it's getting merged with nav & Footer. You can check from link : https://iamsuyashpatel07.github.io/suyashpatel/
AND you can see in image 😁 given below.
![IMG_20201022_151534](https://user-images.githubusercontent.com/59373438/96855213-09540900-147a-11eb-808e-229c6f8aac95.jpg)

**Comment by 013himanshu** [comment]
I have made a pull request with a fix. Please have a look and merge if satisfied with the fixed.
