### ISSUE TITLE
social link in footer not working

### ISSUE THREAD

**Issue by Krishnapro** [iamsuyashpatel07/suyashpatel#19]
social link in footer not working @iamsuyashpatel07

**Comment by Krishnapro** [comment]
I'm working Home page footer social link @iamsuyashpatel07

**Comment by iamsuyashpatel07** [comment]
just wait 1-2 days let me see hacktober fest guidelines for this year, after updating  I will notify you here only. @Krishnapro

**Comment by Krishnapro** [comment]
I have already add social link and push but till now not create pull request. should I wait or make PR. @iamsuyashpatel07

**Comment by iamsuyashpatel07** [comment]
wait for it because I had not updated this repo I have to add tag for it.

**Comment by iamsuyashpatel07** [comment]
@Krishnapro now you can make your pr

**Comment by SHAMUNESH** [comment]
Hey! I would like to contribute, can you please assign it to me

**Comment by parth-verma7** [comment]
Hey, @Krishnapro I would like to work on this issue, can u please assign it to me?
