### ISSUE TITLE
Create contribution.md file

### ISSUE THREAD

**Issue by iamsuyashpatel07** [iamsuyashpatel07/suyashpatel#31]
Contribution.md file should contains
- Project introduction
- how can someone contribute in it
- basic commands for git and github
- learning resources for git and github
- rules for code of conduct
- ending with some motivational quotes

**Comment by AaryanSingh0017** [comment]
I can do it ,plz assign it to me.

**Comment by iamsuyashpatel07** [comment]
Okay @AaryanSingh0017

**Comment by AaryanSingh0017** [comment]
I have created the pull request I hope you like it.

**Comment by iamsuyashpatel07** [comment]
Hey @AaryanSingh0017 why did you closed it

**Comment by AaryanSingh0017** [comment]
So sorry i was i didnt how it closed now its open

**Comment by AaryanSingh0017** [comment]
include me under hacktoberfest label
