### ISSUE TITLE
Missing CODE OF CONDUCT

### ISSUE THREAD

**Issue by swoyam2609** [iamsuyashpatel07/suyashpatel#42]
All the repositories contain a CODE OF CONDUCT that should be followed while contributing to the repo. Its missing for this repository

**Comment by PrinceX04** [comment]
@iamsuyashpatel07  I want to work on this issue. Please assign me

**Comment by adarshcode** [comment]
done

**Comment by swoyam2609** [comment]
> done

Actually @PrinceX04 asked for assigning not me. Can you please change the assigned persona

**Comment by adarshcode** [comment]
done

**Comment by PrinceX04** [comment]
Okay

**Comment by PrinceX04** [comment]
As per the issue the issue , I have added the Code of Conduct. Please accept my PR.
