### ISSUE TITLE
Link educational.html and filmography.html

### ISSUE THREAD

**Issue by iamsuyashpatel07** [iamsuyashpatel07/suyashpatel#5]
Create a folder with name blog and add in it educational.html and filmography.html in it and link with the index.html so that clicking on navbutton educational or filmography we redirect on there .html page. educational.html and filmography.html page should have designed in such manner so that it have same navbar and footer as index.html and in body add your name under h1 tag. For getting more clear you can look at:- https://iamsuyashpatel07.github.io/suyashpatel/

**Comment by saraogipraveen** [comment]
I can take this up @iamsuyashpatel07 , Please assign

**Comment by iamsuyashpatel07** [comment]
Okay go ahead.

**Comment by Pakeetharan** [comment]
Pull request opened for this issue 👍

**Comment by iamsuyashpatel07** [comment]
@Pakeetharan thnx

**Comment by iamsuyashpatel07** [comment]
> I can take this up @iamsuyashpatel07 , Please assign
Sorr
