### ISSUE TITLE
Link Portfolio.html

### ISSUE THREAD

**Issue by iamsuyashpatel07** [iamsuyashpatel07/suyashpatel#7]
Create a portfolio folder and create a file with name portfolio.html such that it have same navbar and footer as index.htm page having i.e home page and add your name in body under h1 tag.

**Comment by chadrackkyungu** [comment]
@iamsuyashpatel07 hey can i contribute to this issue?

**Comment by iamsuyashpatel07** [comment]
Yes,you can.

**Comment by iamsuyashpatel07** [comment]
hey @chadrackkyungu  before you @Pakeetharan  had contributed for portfolio page. So if you like to contribute then please contribute for blog.
